/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
        "clickHandler": (e: MouseEvent) => void;
        "dataTestId"?: string;
        "disabled"?: boolean;
        "expand"?: 'block' | 'full';
        "secondary"?: boolean;
        "size"?: 'large' | 'small' | 'default';
        "to"?: string;
        "value": string | number;
    }
    interface AppCamera {
        "expand"?: 'block' | 'full';
    }
    interface AppLanding {
    }
    interface AppLayout {
        "hasBack": boolean;
        "shouldHideFooter": boolean;
    }
    interface AppResult {
    }
    interface AppRoot {
    }
    interface AppSlider {
    }
    interface AppUpload {
    }
}
export interface AppLayoutCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppLayoutElement;
}
export interface AppSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppSliderElement;
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppCameraElement extends Components.AppCamera, HTMLStencilElement {
    }
    var HTMLAppCameraElement: {
        prototype: HTMLAppCameraElement;
        new (): HTMLAppCameraElement;
    };
    interface HTMLAppLandingElement extends Components.AppLanding, HTMLStencilElement {
    }
    var HTMLAppLandingElement: {
        prototype: HTMLAppLandingElement;
        new (): HTMLAppLandingElement;
    };
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppResultElement extends Components.AppResult, HTMLStencilElement {
    }
    var HTMLAppResultElement: {
        prototype: HTMLAppResultElement;
        new (): HTMLAppResultElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSliderElement extends Components.AppSlider, HTMLStencilElement {
    }
    var HTMLAppSliderElement: {
        prototype: HTMLAppSliderElement;
        new (): HTMLAppSliderElement;
    };
    interface HTMLAppUploadElement extends Components.AppUpload, HTMLStencilElement {
    }
    var HTMLAppUploadElement: {
        prototype: HTMLAppUploadElement;
        new (): HTMLAppUploadElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-camera": HTMLAppCameraElement;
        "app-landing": HTMLAppLandingElement;
        "app-layout": HTMLAppLayoutElement;
        "app-result": HTMLAppResultElement;
        "app-root": HTMLAppRootElement;
        "app-slider": HTMLAppSliderElement;
        "app-upload": HTMLAppUploadElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        "clickHandler"?: (e: MouseEvent) => void;
        "dataTestId"?: string;
        "disabled"?: boolean;
        "expand"?: 'block' | 'full';
        "secondary"?: boolean;
        "size"?: 'large' | 'small' | 'default';
        "to"?: string;
        "value"?: string | number;
    }
    interface AppCamera {
        "expand"?: 'block' | 'full';
    }
    interface AppLanding {
    }
    interface AppLayout {
        "hasBack"?: boolean;
        "onNavBackAction"?: (event: AppLayoutCustomEvent<any>) => void;
        "shouldHideFooter"?: boolean;
    }
    interface AppResult {
    }
    interface AppRoot {
    }
    interface AppSlider {
        "onCurrentSlideIndex"?: (event: AppSliderCustomEvent<number>) => void;
    }
    interface AppUpload {
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-camera": AppCamera;
        "app-landing": AppLanding;
        "app-layout": AppLayout;
        "app-result": AppResult;
        "app-root": AppRoot;
        "app-slider": AppSlider;
        "app-upload": AppUpload;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-camera": LocalJSX.AppCamera & JSXBase.HTMLAttributes<HTMLAppCameraElement>;
            "app-landing": LocalJSX.AppLanding & JSXBase.HTMLAttributes<HTMLAppLandingElement>;
            "app-layout": LocalJSX.AppLayout & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-result": LocalJSX.AppResult & JSXBase.HTMLAttributes<HTMLAppResultElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-slider": LocalJSX.AppSlider & JSXBase.HTMLAttributes<HTMLAppSliderElement>;
            "app-upload": LocalJSX.AppUpload & JSXBase.HTMLAttributes<HTMLAppUploadElement>;
        }
    }
}
