/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Plate } from "./components/user-input/user-input";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ConfirmationPage {
    }
    interface PageOne {
    }
    interface SlidesPhoto {
    }
    interface UserInput {
        "answer": HTMLIonInputElement;
        "plate": Plate;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLConfirmationPageElement extends Components.ConfirmationPage, HTMLStencilElement {
    }
    var HTMLConfirmationPageElement: {
        prototype: HTMLConfirmationPageElement;
        new (): HTMLConfirmationPageElement;
    };
    interface HTMLPageOneElement extends Components.PageOne, HTMLStencilElement {
    }
    var HTMLPageOneElement: {
        prototype: HTMLPageOneElement;
        new (): HTMLPageOneElement;
    };
    interface HTMLSlidesPhotoElement extends Components.SlidesPhoto, HTMLStencilElement {
    }
    var HTMLSlidesPhotoElement: {
        prototype: HTMLSlidesPhotoElement;
        new (): HTMLSlidesPhotoElement;
    };
    interface HTMLUserInputElement extends Components.UserInput, HTMLStencilElement {
    }
    var HTMLUserInputElement: {
        prototype: HTMLUserInputElement;
        new (): HTMLUserInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "confirmation-page": HTMLConfirmationPageElement;
        "page-one": HTMLPageOneElement;
        "slides-photo": HTMLSlidesPhotoElement;
        "user-input": HTMLUserInputElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ConfirmationPage {
    }
    interface PageOne {
    }
    interface SlidesPhoto {
    }
    interface UserInput {
        "answer"?: HTMLIonInputElement;
        "plate"?: Plate;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "confirmation-page": ConfirmationPage;
        "page-one": PageOne;
        "slides-photo": SlidesPhoto;
        "user-input": UserInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "confirmation-page": LocalJSX.ConfirmationPage & JSXBase.HTMLAttributes<HTMLConfirmationPageElement>;
            "page-one": LocalJSX.PageOne & JSXBase.HTMLAttributes<HTMLPageOneElement>;
            "slides-photo": LocalJSX.SlidesPhoto & JSXBase.HTMLAttributes<HTMLSlidesPhotoElement>;
            "user-input": LocalJSX.UserInput & JSXBase.HTMLAttributes<HTMLUserInputElement>;
        }
    }
}
