name: Android build process

on:
  push:
    branches: [appflow-cicd]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Build Android on Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: ${{ secrets.IONIC_APP_ID }}
          platform: Android
          build-type: debug
          upload-artifact: Build-Android.zip
          env-vars: {IOS_VERSION: ${{runner.tag.version}}}

  build-ios:
    name: Build iOS
    runs-on: ubuntu-latest
    steps:
      - name: Build iOS on Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: ${{ secrets.IONIC_APP_ID }}
          platform: iOS
          build-type: app-store
          destinations: TestFlight/App Store
          native-config: Override_BundleId
          certificate: iOSProdCertificate
          upload-artifact: iOS-Build.zip