name: Android build process

on:
  push:
    branches: [appflow-cicd]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Install Ionic-Cloud
        run: curl -fsSL https://ionic.io/get-ionic-cloud-cli | bash

      - name: Trigger build Android
        run: ionic-cloud build android debug --app-id=${{ secrets.IONIC_APP_ID }} --commit=${{ github.sha }} --json
        env:
          IONIC_TOKEN: ${{ secrects.IONIC_TOKEN }}

  # build-ios:
  #   name: Build iOS
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build iOS on Appflow
  #       uses: ionic-team/appflow-build@v1
  #       with:
  #         token: ${{ secrets.APPFLOW_TOKEN }}
  #         app-id: ${{ secrets.IONIC_APP_ID }}
  #         platform: iOS
  #         build-type: app-store
  #         destinations: TestFlight/App Store
  #         native-config: Override_BundleId
  #         certificate: iOSProdCertificate
  #         upload-artifact: iOS-Build.zip