name: Slack Notifications

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  publish-opened-event:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    name: Slack notifications for a new PR
    steps:
      - name: Sends a message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-text: ${{ github.actor }} opened a new PR i.e ${{ github.event.pull_request.head.ref }} in ${{ github.repository }}.

  publish-merge-event:
    if:  ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    name: Slack notifications for a merge
    steps:
      - name: Sends a message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-text: ${{ github.actor }} merged a PR i.e ${{ github.event.pull_request.head.ref }} in ${{ github.repository }}.

